//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbLSkıll
    {
        public int SkıllId { get; set; }
        public string SkıllTable { get; set; }//skill title burası
        public Nullable<byte> SkıllValue { get; set; }///evet skill title da yok müsait m,isin arayabilir miyim evet
    }
}
